import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import styled from 'styled-components';
import { FiBell, FiClock, FiLock, FiPause, FiPlay, FiPlus, FiTrash2, FiX } from 'react-icons/fi';
import api from '../lib/api';
import withAuth from '../components/withAuth';

const TIPOS = {
  PRECO_ACIMA: ['Preço acima de', 'ACIMA', true], PRECO_ABAIXO: ['Preço abaixo de', 'ABAIXO', true],
  VARIACAO_PERCENTUAL: ['Variação percentual', 'QUALQUER', true], MELHOR_BID: ['Melhor bid', 'ACIMA', true],
  MELHOR_ASK: ['Melhor ask', 'ABAIXO', true], SPREAD: ['Spread', 'ABAIXO', true],
  ORDEM_EXECUCAO: ['Execução da ordem', 'QUALQUER', false], IPO_ESGOTANDO: ['IPO próximo do fim', 'ABAIXO', true],
  CLASSIFICACAO: ['Mudança na classificação', 'QUALQUER', false], TOP4: ['Entrada ou saída do Top 4', 'QUALQUER', false],
  DIVIDENDOS: ['Sequência para dividendos', 'ACIMA', true], LIQUIDACAO: ['Proximidade da liquidação', 'ABAIXO', true],
};
const moeda = v => `T$ ${Number(v || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`;

function AlertasPage() {
  const [dados, setDados] = useState(null); const [opcoes, setOpcoes] = useState({ clubes: [], ordens: [] });
  const [historico, setHistorico] = useState([]); const [modal, setModal] = useState(false); const [erro, setErro] = useState('');
  const [salvando, setSalvando] = useState(false); const [form, setForm] = useState({ tipo: 'PRECO_ACIMA', clubeId: '', ordemId: '', valorAlvo: '', nome: '', operador: 'ACIMA', recorrente: true, cooldownMinutos: 60 });
  const carregar = useCallback(async () => {
    setErro(''); try { const { data } = await api.get('/advanced-alerts'); setDados(data); if (data.premium) { const [o, h] = await Promise.all([api.get('/advanced-alerts/opcoes'), api.get('/advanced-alerts/historico')]); setOpcoes(o.data); setHistorico(h.data.historico || []); } } catch (e) { setErro(e?.response?.data?.erro || 'Não foi possível carregar os alertas.'); }
  }, []);
  useEffect(() => { carregar(); }, [carregar]);
  const config = TIPOS[form.tipo];
  const precisaClube = !['ORDEM_EXECUCAO', 'LIQUIDACAO'].includes(form.tipo);
  const precisaValor = config?.[2];
  const criar = async e => { e.preventDefault(); setSalvando(true); setErro(''); try { await api.post('/advanced-alerts', { ...form, operador: form.tipo === 'TOP4' ? form.operador : config?.[1] }); setModal(false); setForm({ tipo: 'PRECO_ACIMA', clubeId: '', ordemId: '', valorAlvo: '', nome: '', operador: 'ACIMA', recorrente: true, cooldownMinutos: 60 }); await carregar(); window.dispatchEvent(new Event('notifications-updated')); } catch (x) { setErro(x?.response?.data?.erro || 'Não foi possível criar o alerta.'); } finally { setSalvando(false); } };
  const alterar = async (id, status) => { await api.patch(`/advanced-alerts/${id}`, { status }); await carregar(); };
  const excluir = async id => { if (!window.confirm('Excluir este alerta e manter o histórico de disparos?')) return; await api.delete(`/advanced-alerts/${id}`); await carregar(); };
  const ativos = useMemo(() => (dados?.alertas || []).filter(a => a.status === 'ATIVO'), [dados]);

  if (!dados) return <Estado><FiBell /><h2>Carregando alertas...</h2></Estado>;
  if (!dados.premium) return <Page><Hero><Eyebrow><FiBell /> Exclusivo Premium</Eyebrow><h1>Alertas avançados</h1><p>Acompanhe mercado, ordens, IPO, classificação e dividendos com regras configuradas por você.</p></Hero><Locked><Preview><i/><i/><i/></Preview><Overlay><Lock><FiLock /></Lock><h2>Antecipe movimentos importantes</h2><p>Crie condições personalizadas e receba notificações diretamente na TradeSports.</p><Upgrade href="/planos">Fazer upgrade</Upgrade></Overlay></Locked></Page>;

  return <Page>
    <Hero><HeroText><Eyebrow><FiBell /> Inteligência Premium</Eyebrow><h1>Alertas avançados</h1><p>Monitore condições estratégicas sem precisar acompanhar cada tela o tempo todo.</p></HeroText><HeroAction><Counter><strong>{ativos.length}</strong><span>de {dados.limiteAtivos} ativos</span></Counter><NewButton onClick={() => setModal(true)}><FiPlus /> Novo alerta</NewButton></HeroAction></Hero>
    {erro && <Error>{erro}</Error>}
    <Tabs><span>Alertas configurados</span><small>Canal atual: plataforma</small></Tabs>
    {(dados.alertas || []).length === 0 ? <Empty><FiBell/><h2>Você ainda não criou alertas</h2><p>Configure sua primeira condição para começar a monitorar.</p><NewButton onClick={() => setModal(true)}><FiPlus/> Criar alerta</NewButton></Empty> : <Grid>{dados.alertas.map(a => <Card key={a._id} $paused={a.status !== 'ATIVO'}><CardTop><Type>{TIPOS[a.tipo]?.[0] || a.tipo}</Type><Status $on={a.status === 'ATIVO'}>{a.status === 'ATIVO' ? 'Ativo' : 'Pausado'}</Status></CardTop><h3>{a.nome}</h3><Meta>{a.clubeNome && <span>{a.clubeNome}</span>} {a.valorAlvo != null && <span>Alvo: {['VARIACAO_PERCENTUAL'].includes(a.tipo) ? `${a.valorAlvo}%` : ['DIVIDENDOS','IPO_ESGOTANDO','LIQUIDACAO'].includes(a.tipo) ? a.valorAlvo : moeda(a.valorAlvo)}</span>}</Meta><Last><FiClock/> {a.ultimoDisparoEm ? `Último disparo: ${new Date(a.ultimoDisparoEm).toLocaleString('pt-BR')}` : 'Ainda não disparou'}</Last><Actions><button onClick={() => alterar(a._id, a.status === 'ATIVO' ? 'PAUSADO' : 'ATIVO')}>{a.status === 'ATIVO' ? <><FiPause/> Pausar</> : <><FiPlay/> Ativar</>}</button><button onClick={() => excluir(a._id)}><FiTrash2/> Excluir</button></Actions></Card>)}</Grid>}
    <History><SectionHead><div><Eyebrow>Histórico</Eyebrow><h2>Disparos recentes</h2></div><small>Últimos 200 eventos</small></SectionHead>{historico.length === 0 ? <HistoryEmpty>Nenhum alerta foi disparado até agora.</HistoryEmpty> : historico.map(h => <HistoryRow key={h._id}><HistoryIcon><FiBell/></HistoryIcon><div><strong>{h.titulo}</strong><p>{h.mensagem}</p></div><time>{new Date(h.disparadoEm).toLocaleString('pt-BR')}</time></HistoryRow>)}</History>
    {modal && <ModalBack onMouseDown={() => setModal(false)}><Modal onMouseDown={e => e.stopPropagation()}><ModalHead><div><Eyebrow>Novo monitoramento</Eyebrow><h2>Criar alerta</h2></div><button onClick={() => setModal(false)}><FiX/></button></ModalHead><form onSubmit={criar}><Field><label>Condição</label><select value={form.tipo} onChange={e => setForm({ ...form, tipo: e.target.value, operador: TIPOS[e.target.value]?.[1] || 'QUALQUER' })}>{Object.entries(TIPOS).map(([k,v]) => <option key={k} value={k}>{v[0]}</option>)}</select></Field>{precisaClube && <Field><label>Clube</label><select required value={form.clubeId} onChange={e => setForm({...form, clubeId:e.target.value})}><option value="">Selecione</option>{opcoes.clubes.map(c => <option key={c._id} value={c._id}>{c.nome}</option>)}</select></Field>}{form.tipo === 'ORDEM_EXECUCAO' && <Field><label>Ordem aberta</label><select required value={form.ordemId} onChange={e => setForm({...form, ordemId:e.target.value})}><option value="">Selecione</option>{opcoes.ordens.map(o => <option key={o._id} value={o._id}>{o.tipo} · {o.quantidade} cotas · {moeda(o.preco)}</option>)}</select></Field>}{form.tipo === 'TOP4' && <Field><label>Evento</label><select value={form.operador} onChange={e => setForm({...form, operador:e.target.value})}><option value="QUALQUER">Entrou ou saiu</option><option value="ENTROU">Entrou no Top 4</option><option value="SAIU">Saiu do Top 4</option></select></Field>}{precisaValor && <Field><label>{form.tipo === 'LIQUIDACAO' ? 'Avisar com quantos dias' : form.tipo === 'DIVIDENDOS' ? 'Rodadas consecutivas' : form.tipo === 'IPO_ESGOTANDO' ? 'Quantidade restante' : form.tipo === 'VARIACAO_PERCENTUAL' ? 'Variação (%)' : 'Valor-alvo'}</label><input type="number" min="0" step="0.01" required value={form.valorAlvo} onChange={e => setForm({...form, valorAlvo:e.target.value})}/></Field>}<Field><label>Nome do alerta</label><input maxLength="100" placeholder="Ex.: Oportunidade Flamengo" value={form.nome} onChange={e => setForm({...form, nome:e.target.value})}/></Field><Two><Field><label>Intervalo mínimo</label><select value={form.cooldownMinutos} onChange={e => setForm({...form,cooldownMinutos:Number(e.target.value)})}><option value={15}>15 minutos</option><option value={60}>1 hora</option><option value={360}>6 horas</option><option value={1440}>24 horas</option></select></Field><Check><input type="checkbox" checked={form.recorrente} onChange={e => setForm({...form,recorrente:e.target.checked})}/><span>Manter recorrente</span></Check></Two><Submit disabled={salvando}>{salvando ? 'Criando...' : 'Criar alerta'}</Submit></form></Modal></ModalBack>}
  </Page>;
}

const Page=styled.main`max-width:1180px;margin:0 auto;padding:34px 24px 70px;color:#eaf1f8;@media(max-width:600px){padding:22px 14px 55px;}`;
const Hero=styled.section`display:flex;justify-content:space-between;gap:28px;align-items:flex-end;padding:30px;border:1px solid rgba(250,204,21,.18);border-radius:22px;background:linear-gradient(135deg,#071728,#0b2238);box-shadow:0 22px 60px rgba(0,0,0,.18);h1{font-size:2.2rem;margin:7px 0 8px;}p{color:#9fb0c2;margin:0;max-width:650px;}@media(max-width:700px){align-items:flex-start;flex-direction:column;padding:22px;h1{font-size:1.75rem;}}`;
const HeroText=styled.div``; const Eyebrow=styled.div`color:#f6d365;text-transform:uppercase;font-weight:900;font-size:.72rem;letter-spacing:.12em;display:flex;gap:7px;align-items:center;`;
const HeroAction=styled.div`display:flex;align-items:center;gap:15px;`; const Counter=styled.div`display:flex;flex-direction:column;text-align:right;strong{font-size:1.45rem;color:#f6d365;}span{font-size:.72rem;color:#8ca0b5;}`;
const NewButton=styled.button`border:0;border-radius:11px;background:linear-gradient(135deg,#e6b94e,#f7d879);color:#152033;padding:12px 17px;font-weight:900;display:inline-flex;gap:7px;align-items:center;cursor:pointer;`;
const Tabs=styled.div`display:flex;justify-content:space-between;margin:28px 2px 13px;span{font-weight:850;}small{color:#8295a8;}`; const Grid=styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px;@media(max-width:760px){grid-template-columns:1fr;}`;
const Card=styled.article`background:#0a1b2c;border:1px solid ${p=>p.$paused?'rgba(148,163,184,.12)':'rgba(246,211,101,.16)'};border-radius:17px;padding:20px;opacity:${p=>p.$paused ? .72 : 1};h3{margin:13px 0 8px;font-size:1.12rem;}`;
const CardTop=styled.div`display:flex;justify-content:space-between;gap:10px;`; const Type=styled.span`font-size:.7rem;color:#f6d365;font-weight:900;text-transform:uppercase;`; const Status=styled.span`font-size:.68rem;padding:4px 8px;border-radius:99px;background:${p=>p.$on?'rgba(0,217,130,.12)':'rgba(148,163,184,.1)'};color:${p=>p.$on?'#57e8ac':'#9caabc'};`;
const Meta=styled.div`display:flex;gap:8px;flex-wrap:wrap;span{background:#10283f;color:#aebdcb;padding:5px 8px;border-radius:7px;font-size:.75rem;}`; const Last=styled.div`display:flex;gap:6px;align-items:center;color:#71869a;font-size:.76rem;margin:15px 0;`; const Actions=styled.div`display:flex;gap:8px;border-top:1px solid rgba(255,255,255,.06);padding-top:13px;button{background:none;border:0;color:#9fb0c2;display:flex;gap:5px;cursor:pointer;padding:4px 8px;&:hover{color:#f6d365;}}`;
const Empty=styled.div`padding:55px 20px;text-align:center;background:#091a2b;border:1px dashed rgba(246,211,101,.18);border-radius:18px;svg{font-size:2rem;color:#f6d365;}p{color:#8295a8;}`;
const History=styled.section`margin-top:35px;background:#081827;border:1px solid rgba(255,255,255,.07);border-radius:18px;padding:22px;`; const SectionHead=styled.div`display:flex;justify-content:space-between;align-items:end;margin-bottom:15px;h2{margin:5px 0 0;}small{color:#75899c;}`; const HistoryEmpty=styled.div`color:#71869a;padding:22px 0;`; const HistoryRow=styled.div`display:grid;grid-template-columns:38px 1fr auto;gap:12px;align-items:center;padding:13px 0;border-top:1px solid rgba(255,255,255,.06);p{margin:3px 0 0;color:#8fa2b4;font-size:.84rem;}time{color:#6f8497;font-size:.72rem;}@media(max-width:600px){grid-template-columns:34px 1fr;time{grid-column:2;}}`; const HistoryIcon=styled.div`width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:rgba(246,211,101,.1);color:#f6d365;`;
const Locked=styled.div`position:relative;min-height:420px;margin-top:25px;overflow:hidden;border-radius:20px;border:1px solid rgba(246,211,101,.15);background:#071727;`; const Preview=styled.div`filter:blur(6px);opacity:.35;padding:35px;display:grid;gap:18px;i{height:90px;border-radius:14px;background:#15334c;}`; const Overlay=styled.div`position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:25px;background:rgba(5,17,29,.72);h2{margin:14px 0 6px;}p{max-width:460px;color:#9aacbd;}`; const Lock=styled.div`width:55px;height:55px;border:1px solid rgba(246,211,101,.4);border-radius:50%;display:grid;place-items:center;color:#f6d365;font-size:1.4rem;background:rgba(246,211,101,.08);`; const Upgrade=styled(Link)`margin-top:12px;padding:11px 18px;border-radius:10px;background:#e8bd57;color:#152033;font-weight:900;text-decoration:none;`;
const ModalBack=styled.div`position:fixed;inset:0;z-index:5000;background:rgba(1,8,15,.8);display:grid;place-items:center;padding:18px;backdrop-filter:blur(5px);`; const Modal=styled.div`width:min(570px,100%);max-height:92vh;overflow:auto;background:#091b2d;border:1px solid rgba(246,211,101,.2);border-radius:20px;padding:24px;box-shadow:0 30px 90px #000;`; const ModalHead=styled.div`display:flex;justify-content:space-between;margin-bottom:18px;h2{margin:5px 0 0;}button{background:none;border:0;color:#9eb0c1;font-size:1.4rem;cursor:pointer;}`; const Field=styled.div`display:flex;flex-direction:column;gap:7px;margin-bottom:14px;label{font-size:.76rem;color:#aebdcb;font-weight:800;}input,select{width:100%;background:#061421;border:1px solid #1b3a53;border-radius:10px;color:#eef4fa;padding:12px;outline:none;&:focus{border-color:#dcb450;}}`; const Two=styled.div`display:grid;grid-template-columns:1fr 1fr;gap:14px;@media(max-width:520px){grid-template-columns:1fr;}`; const Check=styled.label`display:flex;align-items:center;gap:9px;color:#aebdcb;font-size:.82rem;input{accent-color:#dcb450;}`; const Submit=styled.button`width:100%;border:0;border-radius:11px;background:#e7bb54;color:#142031;padding:13px;font-weight:950;cursor:pointer;`; const Error=styled.div`margin:15px 0;background:rgba(248,113,113,.1);border:1px solid rgba(248,113,113,.22);color:#fca5a5;padding:11px;border-radius:10px;`; const Estado=styled.div`min-height:55vh;display:grid;place-content:center;text-align:center;color:#8fa4b8;svg{margin:auto;font-size:2rem;color:#f6d365;}`;

export default withAuth(AlertasPage);
